In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
dataframe = pd.read_csv("/Users/felipepesantez/Documents/development/datasets/singapore_airlines_reviews.csv")

In [5]:
dataframe

,published_date,published_platform,rating,type,text,title,helpful_votes
0,2024-03-12T14:41:14-04:00,Desktop,3,review,We used this airline to go from Singapore to L...,Ok,0
1,2024-03-11T19:39:13-04:00,Desktop,5,review,The service on Singapore Airlines Suites Class...,The service in Suites Class makes one feel lik...,0
2,2024-03-11T12:20:23-04:00,Desktop,1,review,"Booked, paid and received email confirmation f...",Don’t give them your money,0
3,2024-03-11T07:12:27-04:00,Desktop,5,review,"Best airline in the world, seats, food, servic...",Best Airline in the World,0
4,2024-03-10T05:34:18-04:00,Desktop,2,review,Premium Economy Seating on Singapore Airlines ...,Premium Economy Seating on Singapore Airlines ...,0
...,...,...,...,...,...,...,...
9995,2018-08-06T03:48:21-04:00,Desktop,5,review,First part done with Singapore Airlines - acce...,"Flew to NZ 1st half Singapore Airlines, 2nd ha...",1
9996,2018-08-05T22:50:29-04:00,Mobile,5,review,And again a great Flight with Singapore Air. G...,Best Airline,1
9997,2018-08-05T22:47:06-04:00,Desktop,5,review,"We flew business class from Frankfurt, via Sin...",Superb service on Singapore Airlines,1
9998,2018-08-05T20:32:03-04:00,Desktop,4,review,"As always, the A380 aircraft was spotlessly pr...",A Comfortable Fiight Spoiled by lack of adequa...,2
9999,2018-08-05T20:19:51-04:00,Desktop,4,review,"As always, Singapore Airlines has done it agai...",Delivered as expected :),3

In [6]:
dataframe.head()

,published_date,published_platform,rating,type,text,title,helpful_votes
0,2024-03-12T14:41:14-04:00,Desktop,3,review,We used this airline to go from Singapore to L...,Ok,0
1,2024-03-11T19:39:13-04:00,Desktop,5,review,The service on Singapore Airlines Suites Class...,The service in Suites Class makes one feel lik...,0
2,2024-03-11T12:20:23-04:00,Desktop,1,review,"Booked, paid and received email confirmation f...",Don’t give them your money,0
3,2024-03-11T07:12:27-04:00,Desktop,5,review,"Best airline in the world, seats, food, servic...",Best Airline in the World,0
4,2024-03-10T05:34:18-04:00,Desktop,2,review,Premium Economy Seating on Singapore Airlines ...,Premium Economy Seating on Singapore Airlines ...,0

In [7]:
dataframe.head(7)

,published_date,published_platform,rating,type,text,title,helpful_votes
0,2024-03-12T14:41:14-04:00,Desktop,3,review,We used this airline to go from Singapore to L...,Ok,0
1,2024-03-11T19:39:13-04:00,Desktop,5,review,The service on Singapore Airlines Suites Class...,The service in Suites Class makes one feel lik...,0
2,2024-03-11T12:20:23-04:00,Desktop,1,review,"Booked, paid and received email confirmation f...",Don’t give them your money,0
3,2024-03-11T07:12:27-04:00,Desktop,5,review,"Best airline in the world, seats, food, servic...",Best Airline in the World,0
4,2024-03-10T05:34:18-04:00,Desktop,2,review,Premium Economy Seating on Singapore Airlines ...,Premium Economy Seating on Singapore Airlines ...,0
5,2024-03-10T01:16:48-05:00,Desktop,1,review,We booked our flights a full 9 months in advan...,Impossible to get a promised refund,0
6,2024-03-10T00:54:43-05:00,Desktop,5,review,This was a fascinating experience. As I sat in...,WOAH. FLY WITH SQ,0

In [8]:
dataframe.tail()

,published_date,published_platform,rating,type,text,title,helpful_votes
9995,2018-08-06T03:48:21-04:00,Desktop,5,review,First part done with Singapore Airlines - acce...,"Flew to NZ 1st half Singapore Airlines, 2nd ha...",1
9996,2018-08-05T22:50:29-04:00,Mobile,5,review,And again a great Flight with Singapore Air. G...,Best Airline,1
9997,2018-08-05T22:47:06-04:00,Desktop,5,review,"We flew business class from Frankfurt, via Sin...",Superb service on Singapore Airlines,1
9998,2018-08-05T20:32:03-04:00,Desktop,4,review,"As always, the A380 aircraft was spotlessly pr...",A Comfortable Fiight Spoiled by lack of adequa...,2
9999,2018-08-05T20:19:51-04:00,Desktop,4,review,"As always, Singapore Airlines has done it agai...",Delivered as expected :),3

In [10]:
dataframe.info

<bound method DataFrame.info of                  published_date published_platform  rating    type  \
0     2024-03-12T14:41:14-04:00            Desktop       3  review
1     2024-03-11T19:39:13-04:00            Desktop       5  review
2     2024-03-11T12:20:23-04:00            Desktop       1  review
3     2024-03-11T07:12:27-04:00            Desktop       5  review
4     2024-03-10T05:34:18-04:00            Desktop       2  review
...                         ...                ...     ...     ...
9995  2018-08-06T03:48:21-04:00            Desktop       5  review
9996  2018-08-05T22:50:29-04:00             Mobile       5  review
9997  2018-08-05T22:47:06-04:00            Desktop       5  review
9998  2018-08-05T20:32:03-04:00            Desktop       4  review
9999  2018-08-05T20:19:51-04:00            Desktop       4  review

                                                   text  \
0     We used this airline to go from Singapore to L...
1     The service on Singapore Airlines Suites Class...
2     Booked, paid and received email confirmation f...
3     Best airline in the world, seats, food, servic...
4     Premium Economy Seating on Singapore Airlines ...
...                                                 ...
9995  First part done with Singapore Airlines - acce...
9996  And again a great Flight with Singapore Air. G...
9997  We flew business class from Frankfurt, via Sin...
9998  As always, the A380 aircraft was spotlessly pr...
9999  As always, Singapore Airlines has done it agai...

                                                  title  helpful_votes
0                                                    Ok              0
1     The service in Suites Class makes one feel lik...              0
2                            Don’t give them your money              0
3                             Best Airline in the World              0
4     Premium Economy Seating on Singapore Airlines ...              0
...                                                 ...            ...
9995  Flew to NZ 1st half Singapore Airlines, 2nd ha...              1
9996                                       Best Airline              1
9997               Superb service on Singapore Airlines              1
9998  A Comfortable Fiight Spoiled by lack of adequa...              2
9999                           Delivered as expected :)              3

[10000 rows x 7 columns]>

In [11]:
dataframe.describe()

             rating  helpful_votes
count  10000.000000   10000.000000
mean       4.015800       1.275200
std        1.346006       2.721618
min        1.000000       0.000000
25%        3.000000       0.000000
50%        5.000000       1.000000
75%        5.000000       2.000000
max        5.000000     158.000000

In [12]:
dataframe.head()

,published_date,published_platform,rating,type,text,title,helpful_votes
0,2024-03-12T14:41:14-04:00,Desktop,3,review,We used this airline to go from Singapore to L...,Ok,0
1,2024-03-11T19:39:13-04:00,Desktop,5,review,The service on Singapore Airlines Suites Class...,The service in Suites Class makes one feel lik...,0
2,2024-03-11T12:20:23-04:00,Desktop,1,review,"Booked, paid and received email confirmation f...",Don’t give them your money,0
3,2024-03-11T07:12:27-04:00,Desktop,5,review,"Best airline in the world, seats, food, servic...",Best Airline in the World,0
4,2024-03-10T05:34:18-04:00,Desktop,2,review,Premium Economy Seating on Singapore Airlines ...,Premium Economy Seating on Singapore Airlines ...,0

In [13]:
dataframe.columns

Index(['published_date', 'published_platform', 'rating', 'type', 'text',
       'title', 'helpful_votes'],
      dtype='object')

In [18]:
dataframe.rating

0       3
1       5
2       1
3       5
4       2
       ..
9995    5
9996    5
9997    5
9998    4
9999    4
Name: rating, Length: 10000, dtype: int64

In [20]:
dataframe["rating"]

0       3
1       5
2       1
3       5
4       2
       ..
9995    5
9996    5
9997    5
9998    4
9999    4
Name: rating, Length: 10000, dtype: int64

In [21]:
dataframe.head()

,published_date,published_platform,rating,type,text,title,helpful_votes
0,2024-03-12T14:41:14-04:00,Desktop,3,review,We used this airline to go from Singapore to L...,Ok,0
1,2024-03-11T19:39:13-04:00,Desktop,5,review,The service on Singapore Airlines Suites Class...,The service in Suites Class makes one feel lik...,0
2,2024-03-11T12:20:23-04:00,Desktop,1,review,"Booked, paid and received email confirmation f...",Don’t give them your money,0
3,2024-03-11T07:12:27-04:00,Desktop,5,review,"Best airline in the world, seats, food, servic...",Best Airline in the World,0
4,2024-03-10T05:34:18-04:00,Desktop,2,review,Premium Economy Seating on Singapore Airlines ...,Premium Economy Seating on Singapore Airlines ...,0

In [24]:
dataframe.loc[4]

published_date                                2024-03-10T05:34:18-04:00
published_platform                                              Desktop
rating                                                                2
type                                                             review
text                  Premium Economy Seating on Singapore Airlines ...
title                 Premium Economy Seating on Singapore Airlines ...
helpful_votes                                                         0
Name: 4, dtype: object

In [25]:
dataframe.iloc[0]

published_date                                2024-03-12T14:41:14-04:00
published_platform                                              Desktop
rating                                                                3
type                                                             review
text                  We used this airline to go from Singapore to L...
title                                                                Ok
helpful_votes                                                         0
Name: 0, dtype: object

In [28]:
dataframe.iloc[20:51]

,published_date,published_platform,rating,type,text,title,helpful_votes
20,2024-03-01T12:39:26-05:00,Desktop,1,review,Flight SQ 241 - I was treated so rudely by the...,Don’t travel Singapore Airlines or you have si...,0
21,2024-03-01T11:30:33-05:00,Desktop,1,review,I booked a round ticket from singapore airline...,Kings of Scams and false promises.,0
22,2024-02-29T01:02:20-05:00,Desktop,5,review,Although flying with Singapore Airlines is com...,Best staff ever,0
23,2024-02-26T09:49:13-05:00,Desktop,3,review,I was somewhat disappointed by the premium eco...,Underwhelming experience in Singapore Premium ...,2
24,2024-02-22T03:52:54-05:00,Desktop,5,review,I write this review as an appraisal for your (...,GOOD CUSTOMER SERVICE,0
25,2024-02-22T01:11:55-05:00,Desktop,3,review,Singapore Airlines use to be one of my fav air...,Singapore Airlines not that great anymore,1
26,2024-02-21T09:56:24-05:00,Desktop,1,review,I don't expect a great deal of comfort when fl...,Awful,1
27,2024-02-19T19:25:02-05:00,Desktop,1,review,"we,have travelled with sq many times , and al...",Not Happy Singapore Air,0
28,2024-02-18T23:44:52-05:00,Desktop,4,review,Travelled from Man to BKK via Singapore and re...,First class food,1
29,2024-02-18T00:29:30-05:00,Desktop,2,review,The trouble with being voted the best is that ...,Oh dear….,0
30,2024-02-17T07:22:55-05:00,Desktop,3,review,Our past experiences with the airline was soog...,Perfection is hard to keep,1
31,2024-02-16T00:39:41-05:00,Desktop,5,review,I have flown many business class flights on 5-...,Best business class seat,0
32,2024-02-15T18:39:29-05:00,Desktop,1,review,After spending a total of 2 hours on the phone...,Booking flight,0
33,2024-02-15T06:43:45-05:00,Desktop,1,review,What the hell happened to Singapore Airlines!?...,Awful,0
34,2024-02-14T17:34:05-05:00,Desktop,2,review,We were disappointed with the SQ for the follo...,Disappointing Experience with SQ,0
35,2024-02-14T13:11:30-05:00,Desktop,1,review,Third flight of 4 we have on this trip and thi...,Very poor Premium Economy experience - never a...,0
36,2024-02-13T21:25:37-05:00,Desktop,1,review,Singapore Airlines feedback channel is one of ...,Singapore Airline Feedback and Complain hotlin...,0
37,2024-02-08T20:14:48-05:00,Desktop,1,review,It's taken a long time before I could bring my...,Enormously disappointed !!!!,0
38,2024-02-07T07:55:34-05:00,Desktop,5,review,One of the absolute best flights I have ever t...,Amazing Experience,0
39,2024-02-07T06:23:54-05:00,Desktop,2,review,If this is voted the BEST Airline then Aviatio...,FROM FIRST TO WORST!!!! Makes a Greyhound bus ...,0
40,2024-02-06T20:20:29-05:00,Desktop,4,review,Good flight left on time and arrived early foo...,Good airline,0
41,2024-02-06T18:26:14-05:00,Desktop,2,review,I booked premium economy as I wanted more leg ...,Nothing premium about premium economy,1
42,2024-02-04T07:02:08-05:00,Desktop,1,review,We have travelled with Singapore airlines a fe...,Aweful experience,1
43,2024-02-03T22:57:43-05:00,Desktop,3,review,Use to love this Airline but the this experien...,What has happened to this Airline,0
44,2024-02-03T21:59:31-05:00,Desktop,2,review,We purchased a round trip tickets. From Jakart...,IMPROVE YOUR SERVICE duh!,1
45,2024-02-03T14:43:38-05:00,Desktop,3,review,Overall a good airline and staff are always ve...,Upgrade to Premium Economy again,0
46,2024-02-03T11:10:37-05:00,Desktop,5,review,"All Cabin Crews were unbelievably welcoming, p...",Top notch service,0
47,2024-02-02T12:13:00-05:00,Desktop,4,review,Everything about our trip was amazing other th...,Great Service - Terrible Aircraft,1
48,2024-02-01T23:53:41-05:00,Desktop,1,review,The worst business class seat we have ever exp...,A380 Business class seats are the most uncomfo...,0
49,2024-02-01T19:27:19-05:00,Desktop,5,review,I can only say the help we received from the s...,Patient and professional,0
50,2024-02-01T10:28:20-05:00,Desktop,2,review,I booked a ticket from Brussels to Perth with ...,Look for another Airline if you can,0